// flow-typed signature: 31304a9ac8ca3deda0273d933d72f010
// flow-typed version: <<STUB>>/gapi-client_v0.0.3/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gapi-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gapi-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gapi-client/index' {
  declare module.exports: $Exports<'gapi-client'>;
}
declare module 'gapi-client/index.js' {
  declare module.exports: $Exports<'gapi-client'>;
}
